<?php
$title = 'Add new car';
$this->headTitle($title);
?>
<header>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <a href="<?= $this->url('car', ['action' => 'index']) ?>" class="action">Back to All Cars</a>
</header>
<?php
// This provides a default CSS class and placeholder text for the title element:
$car = $form->get('name');
$car->setAttribute('class', 'form-control');
$car->setAttribute('placeholder', 'Car name');

// This provides a default CSS class and placeholder text for the artist element:
$model = $form->get('model');
$model->setAttribute('class', 'form-control');
$model->setAttribute('placeholder', 'Model');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('car', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within 
?>
<div class="form-group">
    <?= $this->formLabel($car) ?>
    <?= $this->formElement($car) ?>
    <?= $this->formElementErrors()->render($car, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($model) ?>
    <?= $this->formElement($model) ?>
    <?= $this->formElementErrors()->render($model, ['class' => 'help-block']) ?>
</div>
<br />
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
