<?php

$title = 'Delete car';
$url   = $this->url('car', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<header>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <a href="<?= $this->url('car', ['action' => 'index']) ?>" class="action">
        Back to All Cars
    </a>
</header>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($car->name) ?>" -
    "<?= $this->escapeHtml($car->model) ?>"?
</p>
<br />
<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $car->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>